version: "2"
services:
  home:
    restart: always
    build: .
        args:
          SERVER_IP= ${SERVER_IP}
    ports:
      - "8012:80"
    networks:
      - backend_network
networks:
  backend_network:
    external: true