version: "2"
services:
  home:
    restart: always
    build: .
    ports:
      - "8012:80"
    args:
        SERVER_IP= ${SERVER_IP}
    networks:
      - backend_network
networks:
  backend_network:
    external: true